name: MAXWAVE
trainer: fixed_time_baseline
kind: baseline

supports:
  action_space: [discrete]
  obs_space: [graph, vector]

env_overrides:
  benchmark_mode: resco
  observation_mode: wave
  reward_mode: wait
  step_length: 10
  benchmark_max_distance: 50
