name: STOCHASTIC
trainer: fixed_time_baseline
kind: baseline

supports:
  action_space: [discrete]
  obs_space: [graph, vector]

env_overrides:
  benchmark_mode: resco
  observation_mode: mplight
  reward_mode: wait
  step_length: 5
  benchmark_max_distance: 200
