"""Train the Local-Neighbor GAT Discrete SAC baseline with a raw loop.

Wires together:
    - ``TrafficSignalEnv`` over real SUMO (via libsumo, no GUI)
    - ``LocalNeighborGATDiscreteSAC`` (local encoder + neighbor GAT + fusion)
    - Discrete SAC losses, replay, and manual optimization steps

Requirements
------------
- ``libsumo`` available in the active Python env (``import libsumo`` must work)
- ``nets/grid5x5/`` generated by ``python scripts/build_network.py``

Outputs
-------
- Console logs (every ``--log-interval`` episodes)
- ``<out-dir>/train_log.csv``  — per-episode metrics
- ``<out-dir>/best_agent.pt``  — checkpoint of best-return agent state dict
"""

from __future__ import annotations

import collections
from collections.abc import Mapping
import csv
import gc
import random
import time
from pathlib import Path
from typing import Any

from omegaconf import DictConfig, OmegaConf

from config_utils import load_dotenv, maybe_to_container, resolve_repo_path

load_dotenv()

import torch
from tensordict import TensorDict
from torch import Tensor

from marl_env.observation_adapter import GraphMetadata, ObservationAdapter  # noqa: E402
from marl_env.sumo_env import TrafficSignalEnv  # noqa: E402
from models.local_neighbor_gat_discrete_sac import LocalNeighborGATDiscreteSAC  # noqa: E402
from rl.losses import DiscreteSACLossComputer  # noqa: E402
from rl.optimizers import make_optimizer  # noqa: E402
from train.training_logging import (  # noqa: E402
    TRAIN_LOG_FIELDNAMES,
    build_train_log_row,
    build_train_wandb_payload,
    print_train_progress,
)
from train.postprocess import postprocess_after_training  # noqa: E402
from train.wandb_utils import SafeWandbRun  # noqa: E402


def _build_environment(cfg: DictConfig, out_dir: Path) -> TrafficSignalEnv:
    additional_files = maybe_to_container(cfg.env.additional_files)
    return TrafficSignalEnv(
        net_file=cfg.env.net_file,
        route_file=cfg.env.route_file,
        delta_t=int(cfg.env.delta_t),
        step_length=int(cfg.env.step_length)
        if getattr(cfg.env, "step_length", None) is not None
        else None,
        reward_name=cfg.env.reward_name,
        yellow_duration=int(cfg.env.yellow_duration),
        all_red_duration=int(cfg.env.all_red_duration),
        min_green_duration=int(cfg.env.min_green_duration),
        sumo_binary=cfg.env.sumo_binary,
        gui=bool(cfg.env.gui),
        begin_time=int(cfg.env.begin_time),
        end_time=int(cfg.env.end_time),
        additional_files=additional_files,
        timeloss_subscription_policy=str(
            getattr(cfg.env, "timeloss_subscription_policy", "strict")
        ),
        max_distance=int(getattr(cfg.env, "max_distance", 200)),
        output_dir=str(out_dir),
    )


def _build_observation_pipeline(
    env: TrafficSignalEnv,
    cfg: DictConfig,
    device: torch.device,
) -> tuple[ObservationAdapter, str, GraphMetadata, int]:
    td0 = env.reset()
    graph_metadata = env.get_graph_metadata()

    observation_adapter_cfg = maybe_to_container(
        cfg.model.get("observation_adapter", {})
    ) or {}
    feature_mode = str(observation_adapter_cfg.get("feature_mode", "snapshot"))

    adapter = ObservationAdapter(
        signal_specs=env.get_signal_specs(),
        tl_ids=env.tl_ids,
        layout=env.observation_layout,
        graph_metadata=graph_metadata,
    )

    obs_dim = int(
        adapter.graph_features(
            td0["agents", "observation"].to(device),
            feature_mode=feature_mode,
        ).shape[-1]
    )
    return adapter, feature_mode, graph_metadata, obs_dim


def _build_agent(
    cfg: DictConfig,
    *,
    obs_dim: int,
    num_actions: int,
    device: torch.device,
) -> LocalNeighborGATDiscreteSAC:
    local_encoder_cfg = maybe_to_container(cfg.model.get("local_encoder_cfg", {}))
    neighbor_encoder_cfg = maybe_to_container(
        cfg.model.get("neighbor_encoder_cfg", {})
    )
    fusion_cfg = maybe_to_container(cfg.model.get("fusion_cfg", {}))
    actor_cfg = maybe_to_container(cfg.model.actor_cfg)
    critic_cfg = maybe_to_container(cfg.model.critic_cfg)

    return LocalNeighborGATDiscreteSAC(
        obs_dim=obs_dim,
        num_actions=num_actions,
        local_encoder_cfg=local_encoder_cfg,
        neighbor_encoder_cfg=neighbor_encoder_cfg,
        fusion_cfg=fusion_cfg,
        actor_cfg=actor_cfg,
        critic_cfg=critic_cfg,
        init_alpha=float(cfg.model.init_alpha),
        tau=float(cfg.model.tau),
    ).to(device)


def _build_optimizers(
    cfg: DictConfig,
    agent: LocalNeighborGATDiscreteSAC,
) -> tuple[Mapping[str, torch.optim.Optimizer], str, str]:
    base_optimizer_name = str(cfg.train.optimizer.name)
    optim_actor_cfg = maybe_to_container(
        cfg.train.get("optimizer_actor", cfg.train.optimizer)
    )
    optim_critic_cfg = maybe_to_container(
        cfg.train.get("optimizer_critic", cfg.train.optimizer)
    )
    optim_alpha_cfg = maybe_to_container(
        cfg.train.get("optimizer_alpha", cfg.train.optimizer)
    )

    encoder_actor_params = (
        list(agent.local_encoder.parameters())
        + list(agent.neighbor_encoder.parameters())
        + list(agent.fusion.parameters())
        + list(agent.actor.parameters())
    )

    optimizers = {
        "actor": make_optimizer(encoder_actor_params, optim_actor_cfg),
        "critic": make_optimizer(agent.critic.parameters(), optim_critic_cfg),
        "alpha": make_optimizer([agent.log_alpha], optim_alpha_cfg),
    }

    actor_opt_name = str(optim_actor_cfg.get("name", base_optimizer_name))
    critic_opt_name = str(optim_critic_cfg.get("name", base_optimizer_name))
    return optimizers, actor_opt_name, critic_opt_name


def _build_loss_and_replay(
    cfg: DictConfig,
    *,
    agent: LocalNeighborGATDiscreteSAC,
    seed: int,
) -> tuple[DiscreteSACLossComputer, ReplayBuffer]:
    critic_stability_cfg = maybe_to_container(cfg.train.get("critic_stability", {})) or {}
    loss_fn = DiscreteSACLossComputer(
        agent,
        gamma=float(cfg.train.gamma),
        use_huber_loss=bool(critic_stability_cfg.get("use_huber_loss", False)),
        huber_delta=float(critic_stability_cfg.get("huber_delta", 1.0)),
        clip_target_q=bool(critic_stability_cfg.get("clip_target_q", False)),
        target_q_min=float(critic_stability_cfg.get("target_q_min", -1000.0)),
        target_q_max=float(critic_stability_cfg.get("target_q_max", 1000.0)),
    )
    replay = ReplayBuffer(int(cfg.train.replay_capacity), seed=seed)
    return loss_fn, replay


def _init_wandb(
    cfg: DictConfig,
    *,
    enabled: bool,
    out_dir: Path,
    device: torch.device,
    n_agents: int,
    obs_dim: int,
    num_actions: int,
    n_edges: int,
    actor_opt_name: str,
    critic_opt_name: str,
    reward_name: str,
    feature_mode: str,
    seed: int,
) -> SafeWandbRun:
    wandb_run = SafeWandbRun(enabled=enabled)
    if not wandb_run.enabled:
        return wandb_run

    run_name = cfg.wandb.run_name
    if not run_name:
        run_name = (
            f"gat_a{actor_opt_name}_c{critic_opt_name}_{reward_name}_seed{seed}"
        )

    wandb_cfg_raw = OmegaConf.to_container(cfg, resolve=True)
    wandb_cfg: dict[str, Any] | None = None
    if isinstance(wandb_cfg_raw, dict):
        wandb_cfg = {str(k): v for k, v in wandb_cfg_raw.items()}

    run_metadata: dict[str, Any] = {
        "device": str(device),
        "n_agents": n_agents,
        "obs_dim": obs_dim,
        "num_actions": num_actions,
        "graph_edges": n_edges,
        "run_name": str(run_name),
        "optimizer_actor": actor_opt_name,
        "optimizer_critic": critic_opt_name,
        "reward_name": reward_name,
        "feature_mode": feature_mode,
    }
    wandb_run.init_training_run(
        project=str(cfg.wandb.project),
        run_name=str(run_name),
        run_config=wandb_cfg,
        out_dir=out_dir,
        tags=[
            "gat",
            "discrete-sac",
            "resco",
            actor_opt_name,
            critic_opt_name,
            reward_name,
            feature_mode,
        ],
        run_metadata=run_metadata,
    )
    return wandb_run


def _open_train_log(out_dir: Path) -> tuple[Path, Any, csv.DictWriter]:
    out_dir.mkdir(parents=True, exist_ok=True)
    log_path = out_dir / "train_log.csv"
    log_file = log_path.open("w", newline="")
    writer = csv.DictWriter(log_file, fieldnames=TRAIN_LOG_FIELDNAMES)
    writer.writeheader()
    return log_path, log_file, writer


# ======================================================================
# Replay buffer
# ======================================================================


class ReplayBuffer:
    """Simple FIFO ring buffer storing packed single-step ``TensorDict``s."""

    def __init__(self, capacity: int, seed: int = 0) -> None:
        self._buf: collections.deque[TensorDict] = collections.deque(maxlen=capacity)
        self._rng = random.Random(seed)

    def push(self, transition: TensorDict) -> None:
        self._buf.append(transition.detach().cpu())

    def sample(self, batch_size: int) -> list[TensorDict]:
        k = min(batch_size, len(self._buf))
        return self._rng.sample(list(self._buf), k)

    def __len__(self) -> int:
        return len(self._buf)


# ======================================================================
# Transition helpers
# ======================================================================


def pack_transition(
    td: TensorDict,
    actions: Tensor,
    next_td: TensorDict,
    *,
    graph_observation: Tensor,
    next_graph_observation: Tensor,
    graph_metadata: GraphMetadata,
) -> TensorDict:
    """Pack ``(obs, action, next_obs, reward, done)`` into a replay-ready TensorDict.

    Layout mirrors the schema expected by ``DiscreteSACLossComputer``::

        root
        ├── agents/
        │   ├── observation   [n_agents, obs_dim]
        │   ├── action        [n_agents]
        │   ├── action_mask   [n_agents, num_actions]
        │   ├── reward        [n_agents, 1]
        │   └── done          [n_agents, 1]
        ├── next/agents/
        │   ├── observation   [n_agents, obs_dim]
        │   ├── action_mask   [n_agents, num_actions]
        │   └── done          [n_agents, 1]
        ├── edge_index        [2, E]
        └── edge_attr         [E, 2]   (if present)
    """
    n = int(td["agents", "observation"].shape[0])
    t = TensorDict(
        {
            "agents": TensorDict(
                {
                    "observation": td["agents", "observation"],
                    "action": actions,
                    "action_mask": td["agents", "action_mask"],
                    "reward": next_td["agents", "reward"],
                    "done": next_td["agents", "done"],
                },
                batch_size=[n],
            ),
            "next": TensorDict(
                {
                    "agents": TensorDict(
                        {
                            "observation": next_td["agents", "observation"],
                            "action_mask": next_td["agents", "action_mask"],
                            "done": next_td["agents", "done"],
                        },
                        batch_size=[n],
                    ),
                    "graph_observation": next_graph_observation,
                },
                batch_size=[],
            ),
            "graph_observation": graph_observation,
            "agent_node_indices": graph_metadata.agent_node_indices,
            "agent_node_mask": graph_metadata.agent_node_mask,
            "edge_index": graph_metadata.edge_index,
        },
        batch_size=[],
    )
    if graph_metadata.edge_attr is not None:
        t["edge_attr"] = graph_metadata.edge_attr
    return t


def collate_batch(transitions: list[TensorDict]) -> TensorDict:
    """Stack a list of single-step transitions into a ``[B, N, ...]`` batch.

    ``edge_index`` and ``edge_attr`` are topology tensors shared across all
    batch elements (same 5×5 graph every step).  They are stored once at the
    root with no batch dimension so the loss computer can broadcast them.
    """
    obs    = torch.stack([t["agents", "observation"]   for t in transitions])  # [B,N,D]
    acts   = torch.stack([t["agents", "action"]        for t in transitions])  # [B,N]
    masks  = torch.stack([t["agents", "action_mask"]   for t in transitions])  # [B,N,A]
    rewards= torch.stack([t["agents", "reward"]        for t in transitions])  # [B,N,1]
    dones  = torch.stack([t["agents", "done"]          for t in transitions])  # [B,N,1]

    n_obs   = torch.stack([t["next", "agents", "observation"]  for t in transitions])
    n_masks = torch.stack([t["next", "agents", "action_mask"]  for t in transitions])
    n_dones = torch.stack([t["next", "agents", "done"]         for t in transitions])
    graph_obs = torch.stack([t["graph_observation"] for t in transitions])
    next_graph_obs = torch.stack([t["next", "graph_observation"] for t in transitions])

    B, N = obs.shape[:2]
    # Topology is fixed: take from the first sample and store without batch dim.
    edge_index = transitions[0]["edge_index"]   # [2, E]
    edge_attr  = transitions[0].get("edge_attr", None)  # [E, 2] or None
    agent_node_indices = transitions[0]["agent_node_indices"]
    agent_node_mask = transitions[0]["agent_node_mask"]

    agents_td = TensorDict(
        {"observation": obs, "action": acts, "action_mask": masks,
         "reward": rewards, "done": dones},
        batch_size=[B, N],
    )
    next_agents_td = TensorDict(
        {"observation": n_obs, "action_mask": n_masks, "done": n_dones},
        batch_size=[B, N],
    )
    # Use batch_size=[] for the root to avoid shape conflicts with the
    # fixed-topology edge_index tensor.
    batch = TensorDict(
        {
            "agents": agents_td,
            "next": TensorDict(
                {
                    "agents": next_agents_td,
                    "graph_observation": next_graph_obs,
                },
                batch_size=[],
            ),
            "graph_observation": graph_obs,
            "agent_node_indices": agent_node_indices,
            "agent_node_mask": agent_node_mask,
            "edge_index": edge_index,
        },
        batch_size=[],
    )
    if edge_attr is not None:
        batch["edge_attr"] = edge_attr
    return batch


# ======================================================================
# Episode collection
# ======================================================================


@torch.no_grad()
def run_episode(
    env: TrafficSignalEnv,
    agent: LocalNeighborGATDiscreteSAC,
    device: torch.device,
    adapter: ObservationAdapter,
    feature_mode: str,
    graph_metadata: GraphMetadata,
    *,
    deterministic: bool = False,
) -> tuple[list[TensorDict], float, int, dict[str, float]]:
    """Run one full episode.

    Returns
    -------
    transitions : list[TensorDict]
        Packed single-step transitions (CPU tensors).
    n_steps : int
        Number of RL decision steps taken.
    validation_metrics : dict[str, float]
        Episode-aggregated RESCO benchmark metrics.
    """
    td = env.reset().to(device)
    transitions: list[TensorDict] = []

    while True:
        obs = adapter.graph_features(
            td["agents", "observation"],
            feature_mode=feature_mode,
        ).to(device)
        edge_index = graph_metadata.edge_index.to(device)
        edge_attr = (
            None
            if graph_metadata.edge_attr is None
            else graph_metadata.edge_attr.to(device)
        )
        mask = td["agents", "action_mask"]
        agent_node_indices = graph_metadata.agent_node_indices.to(device)
        agent_node_mask = graph_metadata.agent_node_mask.to(device)

        actions, _ = agent.select_action(
            obs,
            edge_index,
            edge_attr,
            mask,
            deterministic,
            agent_node_indices=agent_node_indices,
            agent_node_mask=agent_node_mask,
        )

        next_td = env.step(actions.cpu()).to(device)
        next_obs = adapter.graph_features(
            next_td["agents", "observation"],
            feature_mode=feature_mode,
        ).to(device)
        transitions.append(
            pack_transition(
                td.cpu(),
                actions.cpu(),
                next_td.cpu(),
                graph_observation=obs.cpu(),
                next_graph_observation=next_obs.cpu(),
                graph_metadata=graph_metadata,
            )
        )

        if next_td["done"].item():
            break
        td = next_td

    validation_metrics = dict(env.get_episode_metrics())
    return transitions, float(validation_metrics.get("global_reward", 0.0)), len(transitions), validation_metrics


# ======================================================================
# SAC update
# ======================================================================


def sac_update(
    loss_fn: DiscreteSACLossComputer,
    replay: ReplayBuffer,
    optimizers: Mapping[str, torch.optim.Optimizer],
    batch_size: int,
    device: torch.device,
) -> dict[str, float] | None:
    """Sample a mini-batch and run one SAC gradient step.

    Returns a metrics dict, or ``None`` if the buffer is too small.
    """
    if len(replay) < batch_size:
        return None

    batch = collate_batch(replay.sample(batch_size)).to(device)
    out = loss_fn.compute(batch)

    optimizers["critic"].zero_grad()
    out.critic_loss.backward()
    torch.nn.utils.clip_grad_norm_(
        loss_fn.agent.critic.parameters(), max_norm=10.0
    )
    optimizers["critic"].step()

    optimizers["actor"].zero_grad()
    out.actor_loss.backward()
    torch.nn.utils.clip_grad_norm_(
        list(loss_fn.agent.local_encoder.parameters())
        + list(loss_fn.agent.neighbor_encoder.parameters())
        + list(loss_fn.agent.fusion.parameters())
        + list(loss_fn.agent.actor.parameters()),
        max_norm=10.0,
    )
    optimizers["actor"].step()

    optimizers["alpha"].zero_grad()
    out.alpha_loss.backward()
    optimizers["alpha"].step()

    loss_fn.agent.soft_update_target()

    return {
        "critic_loss": out.critic_loss.item(),
        "actor_loss":  out.actor_loss.item(),
        "alpha_loss":  out.alpha_loss.item(),
        "q1":          out.q1_mean,
        "q2":          out.q2_mean,
        "entropy":     out.entropy,
        "alpha":       out.alpha,
    }


# ======================================================================
# Training loop
# ======================================================================


def train(cfg: DictConfig) -> dict[str, Any]:
    device = torch.device("cuda" if torch.cuda.is_available() else "cpu")
    seed = int(cfg.train.seed)
    reward_name = str(cfg.env.reward_name)
    print(f"[train_local_neighbor_gat_sac] device={device}")
    print(f"  net:   {cfg.env.net_file}")
    print(f"  route: {cfg.env.route_file}")

    torch.manual_seed(seed)
    random.seed(seed)

    out_dir = resolve_repo_path(cfg.runtime.out_dir)
    env = _build_environment(cfg, out_dir)

    adapter, feature_mode, graph_metadata, obs_dim = _build_observation_pipeline(
        env,
        cfg,
        device,
    )
    num_actions = env.num_actions
    n_agents = env.n_agents
    n_edges = int(graph_metadata.edge_index.shape[1])
    print(
        f"  agents={n_agents}  obs_dim={obs_dim}"
        f"  num_actions={num_actions}  graph_edges={n_edges}"
    )

    agent = _build_agent(
        cfg,
        obs_dim=obs_dim,
        num_actions=num_actions,
        device=device,
    )

    total_params = sum(p.numel() for p in agent.parameters())
    print(f"  agent params: {total_params:,}")
    print("  architecture: local_neighbor_gat_discrete_sac")

    optimizers, actor_opt_name, critic_opt_name = _build_optimizers(cfg, agent)
    loss_fn, replay = _build_loss_and_replay(cfg, agent=agent, seed=seed)

    wandb_run = _init_wandb(
        cfg,
        enabled=bool(cfg.wandb.enabled),
        out_dir=out_dir,
        device=device,
        n_agents=n_agents,
        obs_dim=obs_dim,
        num_actions=num_actions,
        n_edges=n_edges,
        actor_opt_name=actor_opt_name,
        critic_opt_name=critic_opt_name,
        reward_name=reward_name,
        feature_mode=feature_mode,
        seed=seed,
    )

    log_path, log_f, writer = _open_train_log(out_dir)

    # --- Training ---
    best_global_reward = float("-inf")
    total_transitions = 0
    t0 = time.perf_counter()
    interrupted = False
    episodes_completed = 0
    best_ckpt_path = out_dir / "best_agent.pt"

    print(
        f"\n{'Ep':>6}  {'Global R':>12}  {'Avg R':>10}  {'Avg Dur':>10}"
        f"  {'Avg Wait':>10}  {'Avg Loss':>10}  {'Avg Queue':>10}  {'Trans':>9}"
    )
    print("-" * 100)

    try:
        for ep in range(1, int(cfg.train.episodes) + 1):
            agent.train()
            transitions, ep_return, ep_steps, validation_metrics = run_episode(
                env,
                agent,
                device,
                adapter,
                feature_mode,
                graph_metadata,
            )

            for t in transitions:
                replay.push(t)
            total_transitions += len(transitions)

            # --- Gradient updates (one per new transition, after warmup) ---
            if total_transitions >= int(cfg.train.warmup):
                for _ in range(len(transitions) * int(cfg.train.updates_per_step)):
                    m = sac_update(loss_fn, replay, optimizers, int(cfg.train.batch_size), device)
                    if m is None:
                        break

            # --- Checkpoint ---
            if ep_return > best_global_reward:
                best_global_reward = ep_return
                torch.save(agent.state_dict(), best_ckpt_path)

            # --- Log CSV ---
            elapsed = time.perf_counter() - t0
            row = build_train_log_row(
                episode=ep,
                n_steps=ep_steps,
                validation_metrics=validation_metrics,
                total_transitions=total_transitions,
                elapsed_s=elapsed,
            )
            writer.writerow(row)
            log_f.flush()

            # --- W&B ---
            wandb_run.log(
                build_train_wandb_payload(
                    episode=ep,
                    n_steps=ep_steps,
                    validation_metrics=validation_metrics,
                    total_transitions=total_transitions,
                    elapsed_s=elapsed,
                    best_global_reward=best_global_reward,
                )
            )
            # --- Console ---
            if ep % int(cfg.train.log_interval) == 0 or ep == 1:
                print_train_progress(
                    episode=ep,
                    validation_metrics=validation_metrics,
                    total_transitions=total_transitions,
                )
            episodes_completed = ep
    except KeyboardInterrupt:
        interrupted = True
        print("\nTraining interrupted. Finalizing and running post-processing...")
        if not best_ckpt_path.exists():
            torch.save(agent.state_dict(), best_ckpt_path)
            print(f"[interrupt] checkpoint saved -> {best_ckpt_path}")
    finally:
        log_f.close()
        env.close()

    post_cfg = maybe_to_container(cfg.train.get("postprocess", {})) or {}
    post_enabled = bool(post_cfg.get("enabled", True))
    run_on_complete = bool(post_cfg.get("on_complete", True))
    run_on_interrupt = bool(post_cfg.get("on_interrupt", True))
    should_postprocess = post_enabled and ((interrupted and run_on_interrupt) or ((not interrupted) and run_on_complete))

    # Free training graph/optimizer state before post-processing loads models.
    del loss_fn
    del replay
    del optimizers
    del agent
    gc.collect()
    if device.type == "cuda":
        torch.cuda.empty_cache()

    if should_postprocess:
        postprocess_after_training(
            cfg,
            checkpoint_path=best_ckpt_path,
            out_dir=out_dir,
            env_cfg=maybe_to_container(cfg.env),
            model_cfg=maybe_to_container(cfg.model),
            device=device,
            wandb_run=wandb_run,
        )

    if best_ckpt_path.exists():
        wandb_run.save(best_ckpt_path, base_path=out_dir)
    wandb_run.set_summary(
        {
            "interrupted": bool(interrupted),
            "episodes_completed": int(episodes_completed),
            "Best Global Reward": float(best_global_reward),
        }
    )
    exit_code = 1 if interrupted else 0
    wandb_run.finish(exit_code=exit_code)

    print("-" * 100)
    print(f"\nDone.  Best Global Reward: {best_global_reward:.2f}")
    print(f"  checkpoint → {best_ckpt_path}")
    print(f"  log        → {log_path}")

    return {
        "interrupted": interrupted,
        "episodes_completed": episodes_completed,
        "best_checkpoint": str(best_ckpt_path),
        "out_dir": str(out_dir),
    }
