"""Train a GAT-based MARL agent with a raw custom loop.

Wires together:
  - ``TrafficSignalEnv`` over real SUMO (via libsumo, no GUI)
  - ``GraphEncoder`` (2-layer GATv2Conv) — learns graph dynamics
  - ``SharedDiscreteActor`` + ``CentralizedTwinCritic`` (Discrete SAC)
  - Simple ring-buffer replay + manual SAC update loop

Requirements
------------
- ``libsumo`` available in the active Python env (``import libsumo`` must work)
- ``nets/grid5x5/`` generated by ``python scripts/build_network.py``
- Set ``LIBSUMO_AS_TRACI=1`` in the environment (done automatically below)

Outputs
-------
- Console logs (every ``--log-interval`` episodes)
- ``<out-dir>/train_log.csv``  — per-episode metrics
- ``<out-dir>/best_agent.pt``  — checkpoint of best-return agent state dict
"""

from __future__ import annotations

import collections
from collections.abc import Mapping
import csv
import os
import random
import time
from pathlib import Path
from typing import Any

from omegaconf import DictConfig

from config_utils import load_dotenv, maybe_to_container, resolve_repo_path


try:
    import wandb
    _WANDB_AVAILABLE = True
except ImportError:
    _WANDB_AVAILABLE = False

load_dotenv()

# Must be set BEFORE importing marl_env so TraCIAdapter picks up libsumo.
os.environ.setdefault("LIBSUMO_AS_TRACI", "1")

import torch
from tensordict import TensorDict
from torch import Tensor

from marl_env.sumo_env import TrafficSignalEnv  # noqa: E402
from models.marl_discrete_sac import MARLDiscreteSAC  # noqa: E402
from rl.losses import DiscreteSACLossComputer  # noqa: E402
from rl.optimizers import make_optimizer  # noqa: E402


# ======================================================================
# Replay buffer
# ======================================================================


class ReplayBuffer:
    """Simple FIFO ring buffer storing packed single-step ``TensorDict``s."""

    def __init__(self, capacity: int, seed: int = 0) -> None:
        self._buf: collections.deque[TensorDict] = collections.deque(maxlen=capacity)
        self._rng = random.Random(seed)

    def push(self, transition: TensorDict) -> None:
        self._buf.append(transition.detach().cpu())

    def sample(self, batch_size: int) -> list[TensorDict]:
        k = min(batch_size, len(self._buf))
        return self._rng.sample(list(self._buf), k)

    def __len__(self) -> int:
        return len(self._buf)


# ======================================================================
# Transition helpers
# ======================================================================


def pack_transition(
    td: TensorDict,
    actions: Tensor,
    next_td: TensorDict,
) -> TensorDict:
    """Pack ``(obs, action, next_obs, reward, done)`` into a replay-ready TensorDict.

    Layout mirrors the schema expected by ``DiscreteSACLossComputer``::

        root
        ├── agents/
        │   ├── observation   [n_agents, obs_dim]
        │   ├── action        [n_agents]
        │   ├── action_mask   [n_agents, num_actions]
        │   ├── reward        [n_agents, 1]
        │   └── done          [n_agents, 1]
        ├── next/agents/
        │   ├── observation   [n_agents, obs_dim]
        │   ├── action_mask   [n_agents, num_actions]
        │   └── done          [n_agents, 1]
        ├── edge_index        [2, E]
        └── edge_attr         [E, 2]   (if present)
    """
    n = td["agents"].batch_size[0]
    t = TensorDict(
        {
            "agents": TensorDict(
                {
                    "observation": td["agents", "observation"],
                    "action": actions,
                    "action_mask": td["agents", "action_mask"],
                    "reward": next_td["agents", "reward"],
                    "done": next_td["agents", "done"],
                },
                batch_size=[n],
            ),
            "next": TensorDict(
                {
                    "agents": TensorDict(
                        {
                            "observation": next_td["agents", "observation"],
                            "action_mask": next_td["agents", "action_mask"],
                            "done": next_td["agents", "done"],
                        },
                        batch_size=[n],
                    ),
                    "graph_observation": next_td.get(
                        "graph_observation",
                        next_td["agents", "observation"],
                    ),
                },
                batch_size=[],
            ),
            "graph_observation": td.get("graph_observation", td["agents", "observation"]),
            "agent_node_indices": td["agent_node_indices"],
            "agent_node_mask": td["agent_node_mask"],
            "edge_index": td["edge_index"],
        },
        batch_size=[],
    )
    if "edge_attr" in td.keys():
        t["edge_attr"] = td["edge_attr"]
    return t


def collate_batch(transitions: list[TensorDict]) -> TensorDict:
    """Stack a list of single-step transitions into a ``[B, N, ...]`` batch.

    ``edge_index`` and ``edge_attr`` are topology tensors shared across all
    batch elements (same 5×5 graph every step).  They are stored once at the
    root with no batch dimension so the loss computer can broadcast them.
    """
    obs    = torch.stack([t["agents", "observation"]   for t in transitions])  # [B,N,D]
    acts   = torch.stack([t["agents", "action"]        for t in transitions])  # [B,N]
    masks  = torch.stack([t["agents", "action_mask"]   for t in transitions])  # [B,N,A]
    rewards= torch.stack([t["agents", "reward"]        for t in transitions])  # [B,N,1]
    dones  = torch.stack([t["agents", "done"]          for t in transitions])  # [B,N,1]

    n_obs   = torch.stack([t["next", "agents", "observation"]  for t in transitions])
    n_masks = torch.stack([t["next", "agents", "action_mask"]  for t in transitions])
    n_dones = torch.stack([t["next", "agents", "done"]         for t in transitions])
    graph_obs = torch.stack([t["graph_observation"] for t in transitions])
    next_graph_obs = torch.stack([t["next", "graph_observation"] for t in transitions])

    B, N = obs.shape[:2]
    # Topology is fixed: take from the first sample and store without batch dim.
    edge_index = transitions[0]["edge_index"]   # [2, E]
    edge_attr  = transitions[0].get("edge_attr", None)  # [E, 2] or None
    agent_node_indices = transitions[0]["agent_node_indices"]
    agent_node_mask = transitions[0]["agent_node_mask"]

    agents_td = TensorDict(
        {"observation": obs, "action": acts, "action_mask": masks,
         "reward": rewards, "done": dones},
        batch_size=[B, N],
    )
    next_agents_td = TensorDict(
        {"observation": n_obs, "action_mask": n_masks, "done": n_dones},
        batch_size=[B, N],
    )
    # Use batch_size=[] for the root to avoid shape conflicts with the
    # fixed-topology edge_index tensor.
    batch = TensorDict(
        {
            "agents": agents_td,
            "next": TensorDict(
                {
                    "agents": next_agents_td,
                    "graph_observation": next_graph_obs,
                },
                batch_size=[],
            ),
            "graph_observation": graph_obs,
            "agent_node_indices": agent_node_indices,
            "agent_node_mask": agent_node_mask,
            "edge_index": edge_index,
        },
        batch_size=[],
    )
    if edge_attr is not None:
        batch["edge_attr"] = edge_attr
    return batch


# ======================================================================
# Episode collection
# ======================================================================


@torch.no_grad()
def run_episode(
    env: TrafficSignalEnv,
    agent: MARLDiscreteSAC,
    device: torch.device,
    *,
    deterministic: bool = False,
) -> tuple[list[TensorDict], float, int, dict[str, float]]:
    """Run one full episode.

    Returns
    -------
    transitions : list[TensorDict]
        Packed single-step transitions (CPU tensors).
    total_reward : float
        Sum of all agent rewards over the episode.
    n_steps : int
        Number of RL decision steps taken.
    validation_metrics : dict[str, float]
        Episode-aggregated network-level KPIs.
    """
    td = env.reset().to(device)
    transitions: list[TensorDict] = []
    total_reward = 0.0
    avg_metric_keys = (
        "avg_delay_s",
        "avg_queue_length",
        "avg_speed_mps",
        "avg_occupancy_pct",
        "min_expected_vehicles",
        "network_total_waiting_s",
        "network_total_vehicles",
    )
    total_metric_keys = (
        "arrived_vehicles",
        "departed_vehicles",
        "teleported_vehicles",
    )
    metric_sums: dict[str, float] = {k: 0.0 for k in avg_metric_keys + total_metric_keys}
    n_decisions = 0

    while True:
        obs = td.get("graph_observation", td["agents", "observation"])
        edge_index = td["edge_index"]
        edge_attr = td.get("edge_attr", None)
        mask = td["agents", "action_mask"]
        agent_node_indices = td["agent_node_indices"]
        agent_node_mask = td["agent_node_mask"]

        actions, _ = agent.select_action(
            obs,
            edge_index,
            edge_attr,
            mask,
            deterministic,
            agent_node_indices=agent_node_indices,
            agent_node_mask=agent_node_mask,
        )

        next_td = env.step(actions.cpu()).to(device)
        transitions.append(pack_transition(td.cpu(), actions.cpu(), next_td.cpu()))

        total_reward += float(next_td["agents", "reward"].sum().item())
        interval_kpis = env.get_interval_kpis()
        for key in avg_metric_keys + total_metric_keys:
            metric_sums[key] += float(interval_kpis.get(key, 0.0))
        n_decisions += 1

        if next_td["done"].item():
            break
        td = next_td

    episode_kpis = env.get_episode_kpis()
    validation_metrics = {
        "avg_delay_s": metric_sums["avg_delay_s"] / max(n_decisions, 1),
        "avg_queue_length": metric_sums["avg_queue_length"] / max(n_decisions, 1),
        "avg_speed_mps": metric_sums["avg_speed_mps"] / max(n_decisions, 1),
        "avg_occupancy_pct": metric_sums["avg_occupancy_pct"] / max(n_decisions, 1),
        "avg_min_expected_vehicles": metric_sums["min_expected_vehicles"] / max(n_decisions, 1),
        "network_total_waiting_s": metric_sums["network_total_waiting_s"] / max(n_decisions, 1),
        "network_total_vehicles": metric_sums["network_total_vehicles"] / max(n_decisions, 1),
        "total_arrived_vehicles": metric_sums["arrived_vehicles"],
        "total_departed_vehicles": metric_sums["departed_vehicles"],
        "total_teleported_vehicles": metric_sums["teleported_vehicles"],
        "avg_travel_time_s": float(episode_kpis.get("avg_travel_time_s", 0.0)),
    }
    return transitions, total_reward, len(transitions), validation_metrics


# ======================================================================
# SAC update
# ======================================================================


def sac_update(
    loss_fn: DiscreteSACLossComputer,
    replay: ReplayBuffer,
    optimizers: Mapping[str, torch.optim.Optimizer],
    batch_size: int,
    device: torch.device,
) -> dict[str, float] | None:
    """Sample a mini-batch and run one SAC gradient step.

    Returns a metrics dict, or ``None`` if the buffer is too small.
    """
    if len(replay) < batch_size:
        return None

    batch = collate_batch(replay.sample(batch_size)).to(device)
    out = loss_fn.compute(batch)

    optimizers["critic"].zero_grad()
    out.critic_loss.backward()
    torch.nn.utils.clip_grad_norm_(
        loss_fn.agent.critic.parameters(), max_norm=10.0
    )
    optimizers["critic"].step()

    optimizers["actor"].zero_grad()
    out.actor_loss.backward()
    torch.nn.utils.clip_grad_norm_(
        list(loss_fn.agent.encoder.parameters())
        + list(loss_fn.agent.actor.parameters()),
        max_norm=10.0,
    )
    optimizers["actor"].step()

    optimizers["alpha"].zero_grad()
    out.alpha_loss.backward()
    optimizers["alpha"].step()

    return {
        "critic_loss": out.critic_loss.item(),
        "actor_loss":  out.actor_loss.item(),
        "alpha_loss":  out.alpha_loss.item(),
        "q1":          out.q1_mean,
        "q2":          out.q2_mean,
        "entropy":     out.entropy,
        "alpha":       out.alpha,
    }


# ======================================================================
# Training loop
# ======================================================================


def train(cfg: DictConfig) -> None:
    device = torch.device("cuda" if torch.cuda.is_available() else "cpu")
    seed = int(cfg.train.seed)
    base_optimizer_name = str(cfg.train.optimizer.name)
    reward_mode = str(cfg.env.reward_mode)
    print(f"[train_gat_baseline] device={device}")
    print(f"  net:   {cfg.env.net_file}")
    print(f"  route: {cfg.env.route_file}")

    torch.manual_seed(seed)
    random.seed(seed)

    out_dir = resolve_repo_path(cfg.runtime.out_dir)
    additional_files = maybe_to_container(cfg.env.additional_files)

    # --- Environment (real SUMO via libsumo) ---
    env = TrafficSignalEnv(
        net_file=cfg.env.net_file,
        route_file=cfg.env.route_file,
        delta_t=int(cfg.env.delta_t),
        reward_mode=cfg.env.reward_mode,
        reward_weights=maybe_to_container(cfg.env.reward_weights),
        yellow_duration=int(cfg.env.yellow_duration),
        all_red_duration=int(cfg.env.all_red_duration),
        min_green_duration=int(cfg.env.min_green_duration),
        sumo_binary=cfg.env.sumo_binary,
        gui=bool(cfg.env.gui),
        begin_time=int(cfg.env.begin_time),
        end_time=int(cfg.env.end_time),
        additional_files=additional_files,
        graph_builder_mode=str(getattr(cfg.env, "graph_builder_mode", "original")),
    )

    td0 = env.reset()
    obs_dim     = int(td0.get("graph_observation", td0["agents", "observation"]).shape[-1])
    num_actions = env.num_actions
    n_agents    = env.n_agents
    n_edges     = int(td0["edge_index"].shape[1])
    print(
        f"  agents={n_agents}  obs_dim={obs_dim}"
        f"  num_actions={num_actions}  graph_edges={n_edges}"
    )

    # --- Agent ---
    encoder_cfg = maybe_to_container(cfg.model.encoder_cfg)
    actor_cfg = maybe_to_container(cfg.model.actor_cfg)
    critic_cfg = maybe_to_container(cfg.model.critic_cfg)

    agent = MARLDiscreteSAC(
        obs_dim=obs_dim,
        num_actions=num_actions,
        encoder_cfg=encoder_cfg,
        actor_cfg=actor_cfg,
        critic_cfg=critic_cfg,
        init_alpha=float(cfg.model.init_alpha),
        tau=float(cfg.model.tau),
    ).to(device)

    total_params = sum(p.numel() for p in agent.parameters())
    print(f"  agent params: {total_params:,}")

    # --- Optimizers ---
    optim_cfg_default = maybe_to_container(cfg.train.optimizer)
    optim_actor_cfg = maybe_to_container(cfg.train.get("optimizer_actor", cfg.train.optimizer))
    optim_critic_cfg = maybe_to_container(cfg.train.get("optimizer_critic", cfg.train.optimizer))
    optim_alpha_cfg = maybe_to_container(cfg.train.get("optimizer_alpha", cfg.train.optimizer))
    opt_enc_actor = make_optimizer(
        list(agent.encoder.parameters()) + list(agent.actor.parameters()),
        optim_actor_cfg,
    )
    opt_critic = make_optimizer(agent.critic.parameters(), optim_critic_cfg)
    opt_alpha  = make_optimizer([agent.log_alpha], optim_alpha_cfg)
    optimizers = {"actor": opt_enc_actor, "critic": opt_critic, "alpha": opt_alpha}

    actor_opt_name = str(optim_actor_cfg.get("name", base_optimizer_name))
    critic_opt_name = str(optim_critic_cfg.get("name", base_optimizer_name))

    # --- Loss & Replay ---
    loss_fn = DiscreteSACLossComputer(agent, gamma=float(cfg.train.gamma))
    replay  = ReplayBuffer(int(cfg.train.replay_capacity), seed=seed)

    # --- W&B ---
    use_wandb = _WANDB_AVAILABLE and bool(cfg.wandb.enabled)
    if use_wandb:
        run_name = cfg.wandb.run_name
        if not run_name:
            run_name = f"gat_a{actor_opt_name}_c{critic_opt_name}_{reward_mode}_seed{seed}"
        wandb_cfg_raw = OmegaConf.to_container(cfg, resolve=True)
        wandb_cfg: dict[str, Any] | None = None
        if isinstance(wandb_cfg_raw, dict):
            wandb_cfg = {str(k): v for k, v in wandb_cfg_raw.items()}
        wandb.init(
            project=str(cfg.wandb.project),
            name=str(run_name),
            config=wandb_cfg,
            dir=str(out_dir),
            tags=["gat", "discrete-sac", "marl", "sumo-5x5", actor_opt_name, critic_opt_name, reward_mode],
        )
        wandb.define_metric("train/episode")
        wandb.define_metric("train/*", step_metric="train/episode")
        wandb.define_metric("traffic/*", step_metric="train/episode")
        wandb.define_metric("debug/*", step_metric="train/episode")

        run_metadata = {
            "device": str(device),
            "n_agents": n_agents,
            "obs_dim": obs_dim,
            "num_actions": num_actions,
            "graph_edges": n_edges,
            "optimizer_actor": actor_opt_name,
            "optimizer_critic": critic_opt_name,
            "reward_mode": reward_mode,
        }
        wandb.config.update({"run_metadata": run_metadata}, allow_val_change=True)
        run_obj = wandb.run
        if run_obj is not None:
            run_obj.summary["run_name"] = str(run_name)
            run_obj.summary["optimizer_actor"] = actor_opt_name
            run_obj.summary["optimizer_critic"] = critic_opt_name
            run_obj.summary["reward_mode"] = reward_mode
            run_obj.summary["n_agents"] = n_agents
            run_obj.summary["obs_dim"] = obs_dim
            run_obj.summary["num_actions"] = num_actions
            run_obj.summary["graph_edges"] = n_edges

    # --- Logging ---
    out_dir.mkdir(parents=True, exist_ok=True)
    log_path = out_dir / "train_log.csv"
    fieldnames = [
        "episode", "n_steps", "return", "return_ma50",
        "return_per_agent_step",
        "traffic_avg_travel_time_s", "traffic_avg_delay_s", "traffic_avg_queue_length",
        "val_avg_speed_mps", "val_avg_occupancy_pct",
        "val_avg_min_expected_vehicles",
        "traffic_network_total_waiting_s", "traffic_network_total_vehicles",
        "val_total_arrived_vehicles", "val_total_departed_vehicles",
        "val_total_teleported_vehicles",
        "critic_loss", "actor_loss", "alpha_loss",
        "q1", "q2", "entropy", "alpha",
        "total_transitions", "elapsed_s",
    ]
    log_f  = log_path.open("w", newline="")
    writer = csv.DictWriter(log_f, fieldnames=fieldnames)
    writer.writeheader()

    # --- Training ---
    best_return       = float("-inf")
    total_transitions = 0
    return_history: collections.deque[float] = collections.deque(maxlen=50)
    last_metrics: dict[str, Any] = {}
    t0 = time.perf_counter()

    print(f"\n{'Ep':>6}  {'Return':>10}  {'MA-50':>10}  {'CriticL':>9}"
          f"  {'ActorL':>9}  {'Entropy':>9}  {'Alpha':>7}  {'Trans':>7}")
    print("-" * 85)

    for ep in range(1, int(cfg.train.episodes) + 1):
        agent.train()
        transitions, ep_return, ep_steps, validation_metrics = run_episode(env, agent, device)

        for t in transitions:
            replay.push(t)
        total_transitions += len(transitions)

        return_history.append(ep_return)
        ma50 = sum(return_history) / len(return_history)
        return_per_agent_step = ep_return / max(ep_steps * n_agents, 1)

        # --- Gradient updates (one per new transition, after warmup) ---
        if total_transitions >= int(cfg.train.warmup):
            for _ in range(len(transitions) * int(cfg.train.updates_per_step)):
                m = sac_update(loss_fn, replay, optimizers, int(cfg.train.batch_size), device)
                if m is not None:
                    last_metrics = m
            agent.soft_update_target()

        # --- Checkpoint ---
        if ep_return > best_return:
            best_return = ep_return
            torch.save(agent.state_dict(), out_dir / "best_agent.pt")

        # --- Log CSV ---
        elapsed = time.perf_counter() - t0
        row: dict[str, Any] = {
            "episode":           ep,
            "n_steps":           ep_steps,
            "return":            round(ep_return, 3),
            "return_ma50":       round(ma50, 3),
            "return_per_agent_step": round(return_per_agent_step, 6),
            "traffic_avg_travel_time_s": round(validation_metrics["avg_travel_time_s"], 4),
            "traffic_avg_delay_s": round(validation_metrics["avg_delay_s"], 4),
            "traffic_avg_queue_length": round(validation_metrics["avg_queue_length"], 4),
            "val_avg_speed_mps": round(validation_metrics["avg_speed_mps"], 4),
            "val_avg_occupancy_pct": round(validation_metrics["avg_occupancy_pct"], 4),
            "val_avg_min_expected_vehicles": round(validation_metrics["avg_min_expected_vehicles"], 4),
            "traffic_network_total_waiting_s": round(validation_metrics["network_total_waiting_s"], 4),
            "traffic_network_total_vehicles": round(validation_metrics["network_total_vehicles"], 4),
            "val_total_arrived_vehicles": round(validation_metrics["total_arrived_vehicles"], 2),
            "val_total_departed_vehicles": round(validation_metrics["total_departed_vehicles"], 2),
            "val_total_teleported_vehicles": round(validation_metrics["total_teleported_vehicles"], 2),
            "total_transitions": total_transitions,
            "elapsed_s":         round(elapsed, 1),
            **{k: round(float(v), 5) for k, v in last_metrics.items()},
        }
        writer.writerow(row)
        log_f.flush()

        # --- W&B ---
        if use_wandb:
            wandb.log({
                # Preferred descriptive names
                "train/episode":               ep,
                "train/episode_return":        ep_return,
                "train/episode_return_ma50":   ma50,
                "train/return_per_agent_step": return_per_agent_step,
                "train/episode_steps":         ep_steps,
                "train/total_transitions":     total_transitions,
                "train/elapsed_s":             elapsed,
                "train/loss_critic":           last_metrics.get("critic_loss", float("nan")),
                "train/loss_actor":            last_metrics.get("actor_loss",  float("nan")),
                "train/loss_alpha":            last_metrics.get("alpha_loss",  float("nan")),
                "train/q1_mean":               last_metrics.get("q1",          float("nan")),
                "train/q2_mean":               last_metrics.get("q2",          float("nan")),
                "train/policy_entropy":        last_metrics.get("entropy",     float("nan")),
                "train/alpha":                 last_metrics.get("alpha",       float("nan")),
                "train/best_episode_return":   best_return,
                "traffic/avg_travel_time_s": validation_metrics["avg_travel_time_s"],
                "traffic/avg_delay_s": validation_metrics["avg_delay_s"],
                "traffic/avg_queue_length": validation_metrics["avg_queue_length"],
                "traffic/avg_speed_mps": validation_metrics["avg_speed_mps"],
                "traffic/avg_occupancy_pct": validation_metrics["avg_occupancy_pct"],
                "traffic/avg_min_expected_vehicles": validation_metrics["avg_min_expected_vehicles"],
                "traffic/network_total_waiting_s": validation_metrics["network_total_waiting_s"],
                "traffic/network_total_vehicles": validation_metrics["network_total_vehicles"],
                "traffic/throughput_arrived_vehicles": validation_metrics["total_arrived_vehicles"],
                "traffic/flow_departed_vehicles": validation_metrics["total_departed_vehicles"],
                "traffic/teleported_vehicles": validation_metrics["total_teleported_vehicles"],
            })

        # --- Console ---
        if ep % int(cfg.train.log_interval) == 0 or ep == 1:
            cl = last_metrics.get("critic_loss", float("nan"))
            al = last_metrics.get("actor_loss",  float("nan"))
            en = last_metrics.get("entropy",     float("nan"))
            a  = last_metrics.get("alpha",       float("nan"))
            warm_tag = "" if total_transitions >= int(cfg.train.warmup) else " [warmup]"
            print(
                f"{ep:6d}  {ep_return:10.2f}  {ma50:10.2f}"
                f"  {cl:9.4f}  {al:9.4f}  {en:9.4f}  {a:7.4f}"
                f"  {total_transitions:7d}{warm_tag}"
            )

    log_f.close()
    env.close()

    if use_wandb:
        wandb.save(str(out_dir / "best_agent.pt"), base_path=str(out_dir))
        wandb.finish()

    print("-" * 85)
    print(f"\nDone.  Best return: {best_return:.2f}")
    print(f"  checkpoint → {out_dir / 'best_agent.pt'}")
    print(f"  log        → {log_path}")

