"""Train a GAT-based MARL agent with a raw custom loop.

Wires together:
  - ``TrafficSignalEnv`` over real SUMO (via libsumo, no GUI)
  - ``GraphEncoder`` (2-layer GATv2Conv) — learns graph dynamics
  - ``SharedDiscreteActor`` + ``CentralizedTwinCritic`` (Discrete SAC)
  - Simple ring-buffer replay + manual SAC update loop

Requirements
------------
- ``libsumo`` available in the active Python env (``import libsumo`` must work)
- ``nets/grid5x5/`` generated by ``python scripts/build_network.py``

Outputs
-------
- Console logs (every ``--log-interval`` episodes)
- ``<out-dir>/train_log.csv``  — per-episode metrics
- ``<out-dir>/best_agent.pt``  — checkpoint of best-return agent state dict
"""

from __future__ import annotations

import collections
from collections.abc import Mapping
import csv
import gc
import random
import time
from pathlib import Path
from typing import Any

from omegaconf import DictConfig, OmegaConf

from config_utils import load_dotenv, maybe_to_container, resolve_repo_path

load_dotenv()

import torch
from tensordict import TensorDict
from torch import Tensor

from marl_env.sumo_env import TrafficSignalEnv  # noqa: E402
from models.marl_discrete_sac import MARLDiscreteSAC  # noqa: E402
from rl.losses import DiscreteSACLossComputer  # noqa: E402
from rl.optimizers import make_optimizer  # noqa: E402
from train.training_logging import (  # noqa: E402
    TRAIN_LOG_FIELDNAMES,
    build_train_log_row,
    build_train_wandb_payload,
    print_train_progress,
)
from train.postprocess import postprocess_after_training  # noqa: E402
from train.wandb_utils import SafeWandbRun  # noqa: E402


# ======================================================================
# Replay buffer
# ======================================================================


class ReplayBuffer:
    """Simple FIFO ring buffer storing packed single-step ``TensorDict``s."""

    def __init__(self, capacity: int, seed: int = 0) -> None:
        self._buf: collections.deque[TensorDict] = collections.deque(maxlen=capacity)
        self._rng = random.Random(seed)

    def push(self, transition: TensorDict) -> None:
        self._buf.append(transition.detach().cpu())

    def sample(self, batch_size: int) -> list[TensorDict]:
        k = min(batch_size, len(self._buf))
        return self._rng.sample(list(self._buf), k)

    def __len__(self) -> int:
        return len(self._buf)


# ======================================================================
# Transition helpers
# ======================================================================


def pack_transition(
    td: TensorDict,
    actions: Tensor,
    next_td: TensorDict,
) -> TensorDict:
    """Pack ``(obs, action, next_obs, reward, done)`` into a replay-ready TensorDict.

    Layout mirrors the schema expected by ``DiscreteSACLossComputer``::

        root
        ├── agents/
        │   ├── observation   [n_agents, obs_dim]
        │   ├── action        [n_agents]
        │   ├── action_mask   [n_agents, num_actions]
        │   ├── reward        [n_agents, 1]
        │   └── done          [n_agents, 1]
        ├── next/agents/
        │   ├── observation   [n_agents, obs_dim]
        │   ├── action_mask   [n_agents, num_actions]
        │   └── done          [n_agents, 1]
        ├── edge_index        [2, E]
        └── edge_attr         [E, 2]   (if present)
    """
    n = td["agents"].batch_size[0]
    t = TensorDict(
        {
            "agents": TensorDict(
                {
                    "observation": td["agents", "observation"],
                    "action": actions,
                    "action_mask": td["agents", "action_mask"],
                    "reward": next_td["agents", "reward"],
                    "done": next_td["agents", "done"],
                },
                batch_size=[n],
            ),
            "next": TensorDict(
                {
                    "agents": TensorDict(
                        {
                            "observation": next_td["agents", "observation"],
                            "action_mask": next_td["agents", "action_mask"],
                            "done": next_td["agents", "done"],
                        },
                        batch_size=[n],
                    ),
                    "graph_observation": next_td.get(
                        "graph_observation",
                        next_td["agents", "observation"],
                    ),
                },
                batch_size=[],
            ),
            "graph_observation": td.get("graph_observation", td["agents", "observation"]),
            "agent_node_indices": td["agent_node_indices"],
            "agent_node_mask": td["agent_node_mask"],
            "edge_index": td["edge_index"],
        },
        batch_size=[],
    )
    if "edge_attr" in td.keys():
        t["edge_attr"] = td["edge_attr"]
    return t


def collate_batch(transitions: list[TensorDict]) -> TensorDict:
    """Stack a list of single-step transitions into a ``[B, N, ...]`` batch.

    ``edge_index`` and ``edge_attr`` are topology tensors shared across all
    batch elements (same 5×5 graph every step).  They are stored once at the
    root with no batch dimension so the loss computer can broadcast them.
    """
    obs    = torch.stack([t["agents", "observation"]   for t in transitions])  # [B,N,D]
    acts   = torch.stack([t["agents", "action"]        for t in transitions])  # [B,N]
    masks  = torch.stack([t["agents", "action_mask"]   for t in transitions])  # [B,N,A]
    rewards= torch.stack([t["agents", "reward"]        for t in transitions])  # [B,N,1]
    dones  = torch.stack([t["agents", "done"]          for t in transitions])  # [B,N,1]

    n_obs   = torch.stack([t["next", "agents", "observation"]  for t in transitions])
    n_masks = torch.stack([t["next", "agents", "action_mask"]  for t in transitions])
    n_dones = torch.stack([t["next", "agents", "done"]         for t in transitions])
    graph_obs = torch.stack([t["graph_observation"] for t in transitions])
    next_graph_obs = torch.stack([t["next", "graph_observation"] for t in transitions])

    B, N = obs.shape[:2]
    # Topology is fixed: take from the first sample and store without batch dim.
    edge_index = transitions[0]["edge_index"]   # [2, E]
    edge_attr  = transitions[0].get("edge_attr", None)  # [E, 2] or None
    agent_node_indices = transitions[0]["agent_node_indices"]
    agent_node_mask = transitions[0]["agent_node_mask"]

    agents_td = TensorDict(
        {"observation": obs, "action": acts, "action_mask": masks,
         "reward": rewards, "done": dones},
        batch_size=[B, N],
    )
    next_agents_td = TensorDict(
        {"observation": n_obs, "action_mask": n_masks, "done": n_dones},
        batch_size=[B, N],
    )
    # Use batch_size=[] for the root to avoid shape conflicts with the
    # fixed-topology edge_index tensor.
    batch = TensorDict(
        {
            "agents": agents_td,
            "next": TensorDict(
                {
                    "agents": next_agents_td,
                    "graph_observation": next_graph_obs,
                },
                batch_size=[],
            ),
            "graph_observation": graph_obs,
            "agent_node_indices": agent_node_indices,
            "agent_node_mask": agent_node_mask,
            "edge_index": edge_index,
        },
        batch_size=[],
    )
    if edge_attr is not None:
        batch["edge_attr"] = edge_attr
    return batch


# ======================================================================
# Episode collection
# ======================================================================


@torch.no_grad()
def run_episode(
    env: TrafficSignalEnv,
    agent: MARLDiscreteSAC,
    device: torch.device,
    *,
    deterministic: bool = False,
) -> tuple[list[TensorDict], float, int, dict[str, float]]:
    """Run one full episode.

    Returns
    -------
    transitions : list[TensorDict]
        Packed single-step transitions (CPU tensors).
    n_steps : int
        Number of RL decision steps taken.
    validation_metrics : dict[str, float]
        Episode-aggregated RESCO benchmark metrics.
    """
    td = env.reset().to(device)
    transitions: list[TensorDict] = []

    while True:
        obs = td.get("graph_observation", td["agents", "observation"])
        edge_index = td["edge_index"]
        edge_attr = td.get("edge_attr", None)
        mask = td["agents", "action_mask"]
        agent_node_indices = td["agent_node_indices"]
        agent_node_mask = td["agent_node_mask"]

        actions, _ = agent.select_action(
            obs,
            edge_index,
            edge_attr,
            mask,
            deterministic,
            agent_node_indices=agent_node_indices,
            agent_node_mask=agent_node_mask,
        )

        next_td = env.step(actions.cpu()).to(device)
        transitions.append(pack_transition(td.cpu(), actions.cpu(), next_td.cpu()))

        if next_td["done"].item():
            break
        td = next_td

    validation_metrics = dict(env.get_episode_kpis())
    return transitions, float(validation_metrics.get("global_reward", 0.0)), len(transitions), validation_metrics


# ======================================================================
# SAC update
# ======================================================================


def sac_update(
    loss_fn: DiscreteSACLossComputer,
    replay: ReplayBuffer,
    optimizers: Mapping[str, torch.optim.Optimizer],
    batch_size: int,
    device: torch.device,
) -> dict[str, float] | None:
    """Sample a mini-batch and run one SAC gradient step.

    Returns a metrics dict, or ``None`` if the buffer is too small.
    """
    if len(replay) < batch_size:
        return None

    batch = collate_batch(replay.sample(batch_size)).to(device)
    out = loss_fn.compute(batch)

    optimizers["critic"].zero_grad()
    out.critic_loss.backward()
    torch.nn.utils.clip_grad_norm_(
        loss_fn.agent.critic.parameters(), max_norm=10.0
    )
    optimizers["critic"].step()

    optimizers["actor"].zero_grad()
    out.actor_loss.backward()
    torch.nn.utils.clip_grad_norm_(
        list(loss_fn.agent.encoder.parameters())
        + list(loss_fn.agent.actor.parameters()),
        max_norm=10.0,
    )
    optimizers["actor"].step()

    optimizers["alpha"].zero_grad()
    out.alpha_loss.backward()
    optimizers["alpha"].step()

    loss_fn.agent.soft_update_target()

    return {
        "critic_loss": out.critic_loss.item(),
        "actor_loss":  out.actor_loss.item(),
        "alpha_loss":  out.alpha_loss.item(),
        "q1":          out.q1_mean,
        "q2":          out.q2_mean,
        "entropy":     out.entropy,
        "alpha":       out.alpha,
    }


# ======================================================================
# Training loop
# ======================================================================


def train(cfg: DictConfig) -> dict[str, Any]:
    device = torch.device("cuda" if torch.cuda.is_available() else "cpu")
    seed = int(cfg.train.seed)
    base_optimizer_name = str(cfg.train.optimizer.name)
    reward_mode = str(cfg.env.reward_mode)
    if str(getattr(cfg.env, "benchmark_mode", "native")) != "resco":
        raise ValueError("The public training benchmark path requires env.benchmark_mode='resco'.")
    print(f"[train_gat_baseline] device={device}")
    print(f"  net:   {cfg.env.net_file}")
    print(f"  route: {cfg.env.route_file}")

    torch.manual_seed(seed)
    random.seed(seed)

    out_dir = resolve_repo_path(cfg.runtime.out_dir)
    additional_files = maybe_to_container(cfg.env.additional_files)

    # --- Environment (real SUMO via libsumo) ---
    env = TrafficSignalEnv(
        net_file=cfg.env.net_file,
        route_file=cfg.env.route_file,
        delta_t=int(cfg.env.delta_t),
        step_length=int(cfg.env.step_length) if getattr(cfg.env, "step_length", None) is not None else None,
        reward_mode=cfg.env.reward_mode,
        reward_weights=maybe_to_container(cfg.env.reward_weights),
        yellow_duration=int(cfg.env.yellow_duration),
        all_red_duration=int(cfg.env.all_red_duration),
        min_green_duration=int(cfg.env.min_green_duration),
        sumo_binary=cfg.env.sumo_binary,
        gui=bool(cfg.env.gui),
        begin_time=int(cfg.env.begin_time),
        end_time=int(cfg.env.end_time),
        additional_files=additional_files,
        graph_builder_mode=str(getattr(cfg.env, "graph_builder_mode", "original")),
        timeloss_subscription_policy=str(getattr(cfg.env, "timeloss_subscription_policy", "strict")),
        benchmark_mode=str(getattr(cfg.env, "benchmark_mode", "native")),
        observation_mode=str(getattr(cfg.env, "observation_mode", "graph")),
        benchmark_max_distance=int(getattr(cfg.env, "benchmark_max_distance", 200)),
        benchmark_output_dir=str(out_dir),
    )

    td0 = env.reset()
    obs_dim     = int(td0.get("graph_observation", td0["agents", "observation"]).shape[-1])
    num_actions = env.num_actions
    n_agents    = env.n_agents
    n_edges     = int(td0["edge_index"].shape[1])
    print(
        f"  agents={n_agents}  obs_dim={obs_dim}"
        f"  num_actions={num_actions}  graph_edges={n_edges}"
    )

    # --- Agent ---
    encoder_cfg = maybe_to_container(cfg.model.encoder_cfg)
    actor_cfg = maybe_to_container(cfg.model.actor_cfg)
    critic_cfg = maybe_to_container(cfg.model.critic_cfg)

    agent = MARLDiscreteSAC(
        obs_dim=obs_dim,
        num_actions=num_actions,
        encoder_cfg=encoder_cfg,
        actor_cfg=actor_cfg,
        critic_cfg=critic_cfg,
        init_alpha=float(cfg.model.init_alpha),
        tau=float(cfg.model.tau),
    ).to(device)

    total_params = sum(p.numel() for p in agent.parameters())
    print(f"  agent params: {total_params:,}")

    # --- Optimizers ---
    optim_actor_cfg = maybe_to_container(cfg.train.get("optimizer_actor", cfg.train.optimizer))
    optim_critic_cfg = maybe_to_container(cfg.train.get("optimizer_critic", cfg.train.optimizer))
    optim_alpha_cfg = maybe_to_container(cfg.train.get("optimizer_alpha", cfg.train.optimizer))
    opt_enc_actor = make_optimizer(
        list(agent.encoder.parameters()) + list(agent.actor.parameters()),
        optim_actor_cfg,
    )
    opt_critic = make_optimizer(agent.critic.parameters(), optim_critic_cfg)
    opt_alpha  = make_optimizer([agent.log_alpha], optim_alpha_cfg)
    optimizers = {"actor": opt_enc_actor, "critic": opt_critic, "alpha": opt_alpha}

    actor_opt_name = str(optim_actor_cfg.get("name", base_optimizer_name))
    critic_opt_name = str(optim_critic_cfg.get("name", base_optimizer_name))

    # --- Loss & Replay ---
    critic_stability_cfg = maybe_to_container(cfg.train.get("critic_stability", {})) or {}
    loss_fn = DiscreteSACLossComputer(
        agent,
        gamma=float(cfg.train.gamma),
        use_huber_loss=bool(critic_stability_cfg.get("use_huber_loss", False)),
        huber_delta=float(critic_stability_cfg.get("huber_delta", 1.0)),
        clip_target_q=bool(critic_stability_cfg.get("clip_target_q", False)),
        target_q_min=float(critic_stability_cfg.get("target_q_min", -1000.0)),
        target_q_max=float(critic_stability_cfg.get("target_q_max", 1000.0)),
    )
    replay  = ReplayBuffer(int(cfg.train.replay_capacity), seed=seed)

    # --- W&B ---
    wandb_run = SafeWandbRun(enabled=bool(cfg.wandb.enabled))
    if wandb_run.enabled:
        run_name = cfg.wandb.run_name
        if not run_name:
            run_name = f"gat_a{actor_opt_name}_c{critic_opt_name}_{reward_mode}_seed{seed}"
        wandb_cfg_raw = OmegaConf.to_container(cfg, resolve=True)
        wandb_cfg: dict[str, Any] | None = None
        if isinstance(wandb_cfg_raw, dict):
            wandb_cfg = {str(k): v for k, v in wandb_cfg_raw.items()}
        run_metadata: dict[str, Any] = {
            "device": str(device),
            "n_agents": n_agents,
            "obs_dim": obs_dim,
            "num_actions": num_actions,
            "graph_edges": n_edges,
            "run_name": str(run_name),
            "optimizer_actor": actor_opt_name,
            "optimizer_critic": critic_opt_name,
            "reward_mode": reward_mode,
        }
        wandb_run.init_training_run(
            project=str(cfg.wandb.project),
            run_name=str(run_name),
            run_config=wandb_cfg,
            out_dir=out_dir,
            tags=["gat", "discrete-sac", "resco", actor_opt_name, critic_opt_name, reward_mode],
            run_metadata=run_metadata,
        )

    # --- Logging ---
    out_dir.mkdir(parents=True, exist_ok=True)
    log_path = out_dir / "train_log.csv"
    fieldnames = TRAIN_LOG_FIELDNAMES
    log_f  = log_path.open("w", newline="")
    writer = csv.DictWriter(log_f, fieldnames=fieldnames)
    writer.writeheader()

    # --- Training ---
    best_global_reward = float("-inf")
    total_transitions = 0
    last_metrics: dict[str, Any] = {}
    t0 = time.perf_counter()
    interrupted = False
    episodes_completed = 0
    best_ckpt_path = out_dir / "best_agent.pt"

    print(
        f"\n{'Ep':>6}  {'Global R':>12}  {'Avg R':>10}  {'Avg Dur':>10}"
        f"  {'Avg Wait':>10}  {'Avg Loss':>10}  {'Avg Queue':>10}  {'Trans':>9}"
    )
    print("-" * 100)

    try:
        for ep in range(1, int(cfg.train.episodes) + 1):
            agent.train()
            transitions, ep_return, ep_steps, validation_metrics = run_episode(env, agent, device)

            for t in transitions:
                replay.push(t)
            total_transitions += len(transitions)

            # --- Gradient updates (one per new transition, after warmup) ---
            if total_transitions >= int(cfg.train.warmup):
                for _ in range(len(transitions) * int(cfg.train.updates_per_step)):
                    m = sac_update(loss_fn, replay, optimizers, int(cfg.train.batch_size), device)
                    if m is not None:
                        last_metrics = m

            # --- Checkpoint ---
            if ep_return > best_global_reward:
                best_global_reward = ep_return
                torch.save(agent.state_dict(), best_ckpt_path)

            # --- Log CSV ---
            elapsed = time.perf_counter() - t0
            row = build_train_log_row(
                episode=ep,
                n_steps=ep_steps,
                validation_metrics=validation_metrics,
                total_transitions=total_transitions,
                elapsed_s=elapsed,
            )
            writer.writerow(row)
            log_f.flush()

            # --- W&B ---
            wandb_run.log(
                build_train_wandb_payload(
                    episode=ep,
                    n_steps=ep_steps,
                    validation_metrics=validation_metrics,
                    total_transitions=total_transitions,
                    elapsed_s=elapsed,
                    best_global_reward=best_global_reward,
                )
            )
            # --- Console ---
            if ep % int(cfg.train.log_interval) == 0 or ep == 1:
                print_train_progress(
                    episode=ep,
                    validation_metrics=validation_metrics,
                    total_transitions=total_transitions,
                )
            episodes_completed = ep
    except KeyboardInterrupt:
        interrupted = True
        print("\nTraining interrupted. Finalizing and running post-processing...")
        if not best_ckpt_path.exists():
            torch.save(agent.state_dict(), best_ckpt_path)
            print(f"[interrupt] checkpoint saved -> {best_ckpt_path}")
    finally:
        log_f.close()
        env.close()

    post_cfg = maybe_to_container(cfg.train.get("postprocess", {})) or {}
    post_enabled = bool(post_cfg.get("enabled", True))
    run_on_complete = bool(post_cfg.get("on_complete", True))
    run_on_interrupt = bool(post_cfg.get("on_interrupt", True))
    should_postprocess = post_enabled and ((interrupted and run_on_interrupt) or ((not interrupted) and run_on_complete))

    # Free training graph/optimizer state before post-processing loads models.
    del loss_fn
    del replay
    del optimizers
    del agent
    gc.collect()
    if device.type == "cuda":
        torch.cuda.empty_cache()

    if should_postprocess:
        postprocess_after_training(
            cfg,
            checkpoint_path=best_ckpt_path,
            out_dir=out_dir,
            env_cfg=maybe_to_container(cfg.env),
            model_cfg=maybe_to_container(cfg.model),
            device=device,
            wandb_run=wandb_run,
        )

    if best_ckpt_path.exists():
        wandb_run.save(best_ckpt_path, base_path=out_dir)
    wandb_run.set_summary(
        {
            "interrupted": bool(interrupted),
            "episodes_completed": int(episodes_completed),
            "Best Global Reward": float(best_global_reward),
        }
    )
    exit_code = 1 if interrupted else 0
    wandb_run.finish(exit_code=exit_code)

    print("-" * 100)
    print(f"\nDone.  Best Global Reward: {best_global_reward:.2f}")
    print(f"  checkpoint → {best_ckpt_path}")
    print(f"  log        → {log_path}")

    return {
        "interrupted": interrupted,
        "episodes_completed": episodes_completed,
        "best_checkpoint": str(best_ckpt_path),
        "out_dir": str(out_dir),
    }
