defaults:
  - env: sumo
  - scenario: grid4x4
  - model: default
  - _self_

runtime:
  checkpoint_path: null
  episodes: 5
  device: cuda
  gui: false
  out_dir: .

hydra:
  run:
    dir: .
  output_subdir: null
