"""Train a GAT-based MARL agent on the 5×5 SUMO grid environment.

Wires together:
  - ``TrafficSignalEnv`` over real SUMO (via libsumo, no GUI)
  - ``GraphEncoder`` (2-layer GATv2Conv) — learns graph dynamics
  - ``SharedDiscreteActor`` + ``CentralizedTwinCritic`` (Discrete SAC)
  - Simple ring-buffer replay + manual SAC update loop

Requirements
------------
- ``libsumo`` available in the active Python env (``import libsumo`` must work)
- ``nets/grid5x5/`` generated by ``python scripts/build_network.py``
- Set ``LIBSUMO_AS_TRACI=1`` in the environment (done automatically below)

Usage
-----
    # Default: 5×5 grid, configs/env.yaml + configs/model.yaml
    python scripts/train_gat_baseline.py

    # Custom settings
    python scripts/train_gat_baseline.py --episodes 200 --batch-size 128 \\
        --net nets/grid5x5/grid5x5.net.xml \\
        --route nets/grid5x5/grid5x5.rou.xml

Outputs
-------
- Console logs (every ``--log-interval`` episodes)
- ``<out-dir>/train_log.csv``  — per-episode metrics
- ``<out-dir>/best_agent.pt``  — checkpoint of best-return agent state dict
"""

from __future__ import annotations

import collections
import csv
import os
import random
import sys
import time
from pathlib import Path
from typing import Any

import hydra
from omegaconf import DictConfig, OmegaConf

REPO_ROOT = Path(__file__).resolve().parent.parent


def _load_dotenv(path: Path) -> None:
    """Load simple KEY=VALUE pairs from ``path`` into ``os.environ``."""
    if not path.exists():
        return

    for raw_line in path.read_text(encoding="utf-8").splitlines():
        line = raw_line.strip()
        if not line or line.startswith("#"):
            continue
        if line.startswith("export "):
            line = line[len("export "):].strip()
        if "=" not in line:
            continue

        key, value = line.split("=", 1)
        key = key.strip()
        value = value.strip().strip('"').strip("'")
        if key and key not in os.environ:
            os.environ[key] = value


try:
    import wandb
    _WANDB_AVAILABLE = True
except ImportError:
    _WANDB_AVAILABLE = False

_load_dotenv(REPO_ROOT / ".env")

# Must be set BEFORE importing marl_env so TraCIAdapter picks up libsumo.
os.environ.setdefault("LIBSUMO_AS_TRACI", "1")

import torch
from tensordict import TensorDict
from torch import Tensor
from torch.optim import Adam

# ---------------------------------------------------------------------------
# Allow running as a top-level script from the project root
# ---------------------------------------------------------------------------
sys.path.insert(0, str(REPO_ROOT))

from marl_env.sumo_env import TrafficSignalEnv  # noqa: E402
from models.marl_discrete_sac import MARLDiscreteSAC  # noqa: E402
from rl.losses import DiscreteSACLossComputer  # noqa: E402


# ======================================================================
# Replay buffer
# ======================================================================


class ReplayBuffer:
    """Simple FIFO ring buffer storing packed single-step ``TensorDict``s."""

    def __init__(self, capacity: int, seed: int = 0) -> None:
        self._buf: collections.deque[TensorDict] = collections.deque(maxlen=capacity)
        self._rng = random.Random(seed)

    def push(self, transition: TensorDict) -> None:
        self._buf.append(transition.detach().cpu())

    def sample(self, batch_size: int) -> list[TensorDict]:
        k = min(batch_size, len(self._buf))
        return self._rng.sample(list(self._buf), k)

    def __len__(self) -> int:
        return len(self._buf)


# ======================================================================
# Transition helpers
# ======================================================================


def pack_transition(
    td: TensorDict,
    actions: Tensor,
    next_td: TensorDict,
) -> TensorDict:
    """Pack ``(obs, action, next_obs, reward, done)`` into a replay-ready TensorDict.

    Layout mirrors the schema expected by ``DiscreteSACLossComputer``::

        root
        ├── agents/
        │   ├── observation   [n_agents, obs_dim]
        │   ├── action        [n_agents]
        │   ├── action_mask   [n_agents, num_actions]
        │   ├── reward        [n_agents, 1]
        │   └── done          [n_agents, 1]
        ├── next/agents/
        │   ├── observation   [n_agents, obs_dim]
        │   ├── action_mask   [n_agents, num_actions]
        │   └── done          [n_agents, 1]
        ├── edge_index        [2, E]
        └── edge_attr         [E, 2]   (if present)
    """
    n = td["agents"].batch_size[0]
    t = TensorDict(
        {
            "agents": TensorDict(
                {
                    "observation": td["agents", "observation"],
                    "action": actions,
                    "action_mask": td["agents", "action_mask"],
                    "reward": next_td["agents", "reward"],
                    "done": next_td["agents", "done"],
                },
                batch_size=[n],
            ),
            "next": TensorDict(
                {
                    "agents": TensorDict(
                        {
                            "observation": next_td["agents", "observation"],
                            "action_mask": next_td["agents", "action_mask"],
                            "done": next_td["agents", "done"],
                        },
                        batch_size=[n],
                    ),
                },
                batch_size=[],
            ),
            "edge_index": td["edge_index"],
        },
        batch_size=[],
    )
    if "edge_attr" in td.keys():
        t["edge_attr"] = td["edge_attr"]
    return t


def collate_batch(transitions: list[TensorDict]) -> TensorDict:
    """Stack a list of single-step transitions into a ``[B, N, ...]`` batch.

    ``edge_index`` and ``edge_attr`` are topology tensors shared across all
    batch elements (same 5×5 graph every step).  They are stored once at the
    root with no batch dimension so the loss computer can broadcast them.
    """
    obs    = torch.stack([t["agents", "observation"]   for t in transitions])  # [B,N,D]
    acts   = torch.stack([t["agents", "action"]        for t in transitions])  # [B,N]
    masks  = torch.stack([t["agents", "action_mask"]   for t in transitions])  # [B,N,A]
    rewards= torch.stack([t["agents", "reward"]        for t in transitions])  # [B,N,1]
    dones  = torch.stack([t["agents", "done"]          for t in transitions])  # [B,N,1]

    n_obs   = torch.stack([t["next", "agents", "observation"]  for t in transitions])
    n_masks = torch.stack([t["next", "agents", "action_mask"]  for t in transitions])
    n_dones = torch.stack([t["next", "agents", "done"]         for t in transitions])

    B, N = obs.shape[:2]
    # Topology is fixed: take from the first sample and store without batch dim.
    edge_index = transitions[0]["edge_index"]   # [2, E]
    edge_attr  = transitions[0].get("edge_attr", None)  # [E, 2] or None

    agents_td = TensorDict(
        {"observation": obs, "action": acts, "action_mask": masks,
         "reward": rewards, "done": dones},
        batch_size=[B, N],
    )
    next_agents_td = TensorDict(
        {"observation": n_obs, "action_mask": n_masks, "done": n_dones},
        batch_size=[B, N],
    )
    # Use batch_size=[] for the root to avoid shape conflicts with the
    # fixed-topology edge_index tensor.
    batch = TensorDict(
        {
            "agents": agents_td,
            "next": TensorDict({"agents": next_agents_td}, batch_size=[]),
            "edge_index": edge_index,
        },
        batch_size=[],
    )
    if edge_attr is not None:
        batch["edge_attr"] = edge_attr
    return batch


# ======================================================================
# Episode collection
# ======================================================================


@torch.no_grad()
def run_episode(
    env: TrafficSignalEnv,
    agent: MARLDiscreteSAC,
    device: torch.device,
    *,
    deterministic: bool = False,
) -> tuple[list[TensorDict], float, int]:
    """Run one full episode.

    Returns
    -------
    transitions : list[TensorDict]
        Packed single-step transitions (CPU tensors).
    total_reward : float
        Sum of all agent rewards over the episode.
    n_steps : int
        Number of RL decision steps taken.
    """
    td = env.reset().to(device)
    transitions: list[TensorDict] = []
    total_reward = 0.0

    while True:
        obs = td["agents", "observation"]
        edge_index = td["edge_index"]
        edge_attr = td.get("edge_attr", None)
        mask = td["agents", "action_mask"]

        actions, _ = agent.select_action(obs, edge_index, edge_attr, mask, deterministic)

        next_td = env.step(actions.cpu()).to(device)
        transitions.append(pack_transition(td.cpu(), actions.cpu(), next_td.cpu()))

        total_reward += float(next_td["agents", "reward"].sum().item())

        if next_td["done"].item():
            break
        td = next_td

    return transitions, total_reward, len(transitions)


# ======================================================================
# SAC update
# ======================================================================


def sac_update(
    loss_fn: DiscreteSACLossComputer,
    replay: ReplayBuffer,
    optimizers: dict[str, torch.optim.Optimizer],
    batch_size: int,
    device: torch.device,
) -> dict[str, float] | None:
    """Sample a mini-batch and run one SAC gradient step.

    Returns a metrics dict, or ``None`` if the buffer is too small.
    """
    if len(replay) < batch_size:
        return None

    batch = collate_batch(replay.sample(batch_size)).to(device)
    out = loss_fn.compute(batch)

    optimizers["critic"].zero_grad()
    out.critic_loss.backward()
    torch.nn.utils.clip_grad_norm_(
        loss_fn.agent.critic.parameters(), max_norm=10.0
    )
    optimizers["critic"].step()

    optimizers["actor"].zero_grad()
    out.actor_loss.backward()
    torch.nn.utils.clip_grad_norm_(
        list(loss_fn.agent.encoder.parameters())
        + list(loss_fn.agent.actor.parameters()),
        max_norm=10.0,
    )
    optimizers["actor"].step()

    optimizers["alpha"].zero_grad()
    out.alpha_loss.backward()
    optimizers["alpha"].step()

    return {
        "critic_loss": out.critic_loss.item(),
        "actor_loss":  out.actor_loss.item(),
        "alpha_loss":  out.alpha_loss.item(),
        "q1":          out.q1_mean,
        "q2":          out.q2_mean,
        "entropy":     out.entropy,
        "alpha":       out.alpha,
    }


# ======================================================================
# Training loop
# ======================================================================


def train(cfg: DictConfig) -> None:
    device = torch.device("cuda" if torch.cuda.is_available() else "cpu")
    print(f"[train_gat_baseline] device={device}")
    print(f"  net:   {cfg.env.net_file}")
    print(f"  route: {cfg.env.route_file}")

    torch.manual_seed(int(cfg.train.seed))
    random.seed(int(cfg.train.seed))

    out_dir = Path(str(cfg.runtime.out_dir))
    if not out_dir.is_absolute():
        out_dir = REPO_ROOT / out_dir
    additional_files = (
        None
        if cfg.env.additional_files is None
        else OmegaConf.to_container(cfg.env.additional_files, resolve=True)
    )

    # --- Environment (real SUMO via libsumo) ---
    env = TrafficSignalEnv(
        net_file=cfg.env.net_file,
        route_file=cfg.env.route_file,
        delta_t=int(cfg.env.delta_t),
        reward_mode=cfg.env.reward_mode,
        reward_weights=OmegaConf.to_container(cfg.env.reward_weights, resolve=True),
        yellow_duration=int(cfg.env.yellow_duration),
        all_red_duration=int(cfg.env.all_red_duration),
        min_green_duration=int(cfg.env.min_green_duration),
        sumo_binary=cfg.env.sumo_binary,
        gui=bool(cfg.env.gui),
        begin_time=int(cfg.env.begin_time),
        end_time=int(cfg.env.end_time),
        additional_files=additional_files,
    )

    td0 = env.reset()
    obs_dim     = int(td0["agents", "observation"].shape[-1])
    num_actions = env.num_actions
    n_agents    = env.n_agents
    n_edges     = int(td0["edge_index"].shape[1])
    print(
        f"  agents={n_agents}  obs_dim={obs_dim}"
        f"  num_actions={num_actions}  graph_edges={n_edges}"
    )

    # --- Agent ---
    encoder_cfg = OmegaConf.to_container(cfg.model.encoder_cfg, resolve=True)
    actor_cfg = OmegaConf.to_container(cfg.model.actor_cfg, resolve=True)
    critic_cfg = OmegaConf.to_container(cfg.model.critic_cfg, resolve=True)

    agent = MARLDiscreteSAC(
        obs_dim=obs_dim,
        num_actions=num_actions,
        encoder_cfg=encoder_cfg,
        actor_cfg=actor_cfg,
        critic_cfg=critic_cfg,
        init_alpha=float(cfg.model.init_alpha),
        tau=float(cfg.model.tau),
    ).to(device)

    total_params = sum(p.numel() for p in agent.parameters())
    print(f"  agent params: {total_params:,}")

    # --- Optimizers ---
    opt_enc_actor = Adam(
        list(agent.encoder.parameters()) + list(agent.actor.parameters()),
        lr=float(cfg.train.lr),
    )
    opt_critic = Adam(agent.critic.parameters(), lr=float(cfg.train.lr))
    opt_alpha  = Adam([agent.log_alpha], lr=float(cfg.train.lr))
    optimizers = {"actor": opt_enc_actor, "critic": opt_critic, "alpha": opt_alpha}

    # --- Loss & Replay ---
    loss_fn = DiscreteSACLossComputer(agent, gamma=float(cfg.train.gamma))
    replay  = ReplayBuffer(int(cfg.train.replay_capacity), seed=int(cfg.train.seed))

    # --- W&B ---
    use_wandb = _WANDB_AVAILABLE and bool(cfg.wandb.enabled)
    if use_wandb:
        api_key = os.environ.get("WANDB_API_KEY")
        if api_key:
            wandb.login(key=api_key, relogin=True)
        wandb.init(
            project=str(cfg.wandb.project),
            name=cfg.wandb.run_name,
            config=OmegaConf.to_container(cfg, resolve=True),
            dir=str(out_dir),
            tags=["gat", "discrete-sac", "marl", "sumo-5x5"],
        )
        wandb.define_metric("episode")
        wandb.define_metric("*", step_metric="episode")

    # --- Logging ---
    out_dir.mkdir(parents=True, exist_ok=True)
    log_path = out_dir / "train_log.csv"
    fieldnames = [
        "episode", "n_steps", "return", "return_ma50",
        "critic_loss", "actor_loss", "alpha_loss",
        "q1", "q2", "entropy", "alpha",
        "total_transitions", "elapsed_s",
    ]
    log_f  = log_path.open("w", newline="")
    writer = csv.DictWriter(log_f, fieldnames=fieldnames)
    writer.writeheader()

    # --- Training ---
    best_return       = float("-inf")
    total_transitions = 0
    return_history: collections.deque[float] = collections.deque(maxlen=50)
    last_metrics: dict[str, Any] = {}
    t0 = time.perf_counter()

    print(f"\n{'Ep':>6}  {'Return':>10}  {'MA-50':>10}  {'CriticL':>9}"
          f"  {'ActorL':>9}  {'Entropy':>9}  {'Alpha':>7}  {'Trans':>7}")
    print("-" * 85)

    for ep in range(1, int(cfg.train.episodes) + 1):
        agent.train()
        transitions, ep_return, ep_steps = run_episode(env, agent, device)

        for t in transitions:
            replay.push(t)
        total_transitions += len(transitions)

        return_history.append(ep_return)
        ma50 = sum(return_history) / len(return_history)

        # --- Gradient updates (one per new transition, after warmup) ---
        if total_transitions >= int(cfg.train.warmup):
            for _ in range(len(transitions) * int(cfg.train.updates_per_step)):
                m = sac_update(loss_fn, replay, optimizers, int(cfg.train.batch_size), device)
                if m is not None:
                    last_metrics = m
            agent.soft_update_target()

        # --- Checkpoint ---
        if ep_return > best_return:
            best_return = ep_return
            torch.save(agent.state_dict(), out_dir / "best_agent.pt")

        # --- Log CSV ---
        elapsed = time.perf_counter() - t0
        row: dict[str, Any] = {
            "episode":           ep,
            "n_steps":           ep_steps,
            "return":            round(ep_return, 3),
            "return_ma50":       round(ma50, 3),
            "total_transitions": total_transitions,
            "elapsed_s":         round(elapsed, 1),
            **{k: round(float(v), 5) for k, v in last_metrics.items()},
        }
        writer.writerow(row)
        log_f.flush()

        # --- W&B ---
        if use_wandb:
            wandb.log({
                "episode":           ep,
                "return":            ep_return,
                "return_ma50":       ma50,
                "n_steps":           ep_steps,
                "total_transitions": total_transitions,
                "elapsed_s":         elapsed,
                "critic_loss":       last_metrics.get("critic_loss", float("nan")),
                "actor_loss":        last_metrics.get("actor_loss",  float("nan")),
                "alpha_loss":        last_metrics.get("alpha_loss",  float("nan")),
                "q1":                last_metrics.get("q1",          float("nan")),
                "q2":                last_metrics.get("q2",          float("nan")),
                "entropy":           last_metrics.get("entropy",     float("nan")),
                "alpha":             last_metrics.get("alpha",       float("nan")),
                "best_return":       best_return,
            }, step=ep)

        # --- Console ---
        if ep % int(cfg.train.log_interval) == 0 or ep == 1:
            cl = last_metrics.get("critic_loss", float("nan"))
            al = last_metrics.get("actor_loss",  float("nan"))
            en = last_metrics.get("entropy",     float("nan"))
            a  = last_metrics.get("alpha",       float("nan"))
            warm_tag = "" if total_transitions >= int(cfg.train.warmup) else " [warmup]"
            print(
                f"{ep:6d}  {ep_return:10.2f}  {ma50:10.2f}"
                f"  {cl:9.4f}  {al:9.4f}  {en:9.4f}  {a:7.4f}"
                f"  {total_transitions:7d}{warm_tag}"
            )

    log_f.close()
    env.close()

    if use_wandb:
        wandb.save(str(out_dir / "best_agent.pt"), base_path=str(out_dir))
        wandb.finish()

    print("-" * 85)
    print(f"\nDone.  Best return: {best_return:.2f}")
    print(f"  checkpoint → {out_dir / 'best_agent.pt'}")
    print(f"  log        → {log_path}")


@hydra.main(version_base=None, config_path="../configs", config_name="gat_baseline")
def main(cfg: DictConfig) -> None:
    train(cfg)


if __name__ == "__main__":
    main()
