name: sumo_traffic
family: sumo
action_space: discrete
obs_space: snapshot

common:
  delta_t: 10
  step_length: 10
  sumo_binary: sumo
  gui: false
  additional_files: null
  timeloss_subscription_policy: strict
  max_distance: 200
  reward_name: wait

  yellow_duration: 3
  all_red_duration: 2
  min_green_duration: 10
