episodes: 300
gamma: 0.90
batch_size: 64
replay_capacity: 100000
warmup: 5000
updates_per_step: 1
log_interval: 1

optimizer:
  name: adam
  lr: 3.0e-4
  betas: [0.9, 0.999]
  eps: 1.0e-8
  weight_decay: 0.0
  amsgrad: false
  meta:
    hyper_lr: 1.0e-7
    min_lr: 1.0e-6
    max_lr: 1.0e-2

optimizer_actor:
  name: adam
  lr: 1.0e-4
  betas: [0.9, 0.999]
  eps: 1.0e-8
  weight_decay: 0.0
  amsgrad: false

optimizer_critic:
  name: adam
  lr: 3.0e-4
  betas: [0.9, 0.999]
  eps: 1.0e-8
  weight_decay: 0.0
  amsgrad: false

optimizer_alpha:
  name: adam
  lr: 3.0e-4
  betas: [0.9, 0.999]
  eps: 1.0e-8
  weight_decay: 0.0
  amsgrad: false

postprocess:
  enabled: true
  on_complete: true
  on_interrupt: true

  run_evaluation: true
  eval_episodes: 5
  eval_gui: false

  run_visualization: true
  visualization_out_dir: null
  visualization_device: cpu
  visualization_num_snapshots: 5
  visualization_max_hops: null
  visualization_curve_num_samples: null
  visualization_map_num_samples: null
